# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2023_06_22_065726) do

  create_table "recipes", force: :cascade do |t|
    t.string "tittle"
    t.string "description"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "stock_items", force: :cascade do |t|
    t.string   "stock_num"
    t.integer  "vendor_id"
    t.decimal  "total_sales_price"
    t.decimal  "size"
    t.string   "city"
    t.string   "state"
    t.string   "country"
    t.integer  "available",                                       default: 1
    t.string   "cert_num"
    t.string   "shape"
    t.string   "color"
    t.decimal  "meas_length"
    t.decimal  "meas_width"
    t.decimal  "meas_depth"
    t.decimal  "meas_ratio"
    t.string   "image_url"
    t.string   "video_url"
    t.string   "cert_url"
    t.decimal  "price_per_carat"
    t.string   "lab"
    t.string   "treatment"
    t.boolean  "data_integrity",                                  default: false
    t.integer  "sort_priority",                                   default: 10
    t.string   "type"
    t.integer  "master_diamond_id"
    t.decimal  "mount_price"
    t.string   "fancy_color_dominant_color"
    t.string   "fancy_color_secondary_color"
    t.string   "fancy_color_overtone"
    t.string   "fancy_color_intensity"
    t.string   "clarity"
    t.string   "cut"
    t.string   "symmetry"
    t.string   "polish"
    t.decimal  "depth_percent"
    t.decimal  "table_percent"
    t.string   "girdle_min"
    t.string   "girdle_max"
    t.string   "girdle_condition"
    t.string   "culet_size"
    t.string   "culet_condition"
    t.string   "fluor_color"
    t.string   "fluor_intensity"
    t.boolean  "has_cert_file",                                   default: false
    t.string   "currency_code"
    t.string   "currency_symbol"
    t.decimal  "total_sales_price_in_currency"
    t.string   "short_title"
    t.boolean  "is_separable",                                    default: false
    t.decimal  "cash_price"
    t.decimal  "crown_height"
    t.decimal  "crown_angle"
    t.decimal  "pavilion_depth"
    t.decimal  "pavilion_angle"
    t.string   "laser_inscription"
    t.string   "hearts_and_arrows"
    t.string   "cert_comment"
    t.string   "trade_show"
    t.decimal  "cash_discount"
    t.integer  "parcel_stones"
    t.string   "comments"
    t.string   "eye_clean"
    t.decimal  "star_length"
    t.string   "shade"
    t.string   "milky"
    t.string   "inclusion_black"
    t.string   "inclusion_center"
    t.string   "inclusion_open"
    t.datetime "availability_change_date"
    t.decimal  "discount_percent"
    t.decimal  "sell_price"
    t.string   "bgm"
    t.boolean  "hidden",                                          default: false
    t.string   "transcoding_job"
    t.string   "transcoding_status"
    t.json     "transcoded_video_data"
    t.string   "orbital_source_url"
    t.string   "transcoded_video_url"
    t.string   "video_support"
    t.text     "bad_fields"
    t.boolean  "has_bad_data",                                    default: false
    t.text     "data"
    t.decimal  "girdle_percent"
    t.string   "gem_type"
    t.string   "country_of_origin"
    t.string   "pair"
    t.string   "metals"
    t.string   "brand"
    t.string   "history"
    t.datetime "created_at",                                                      null: false
    t.datetime "updated_at",                                                      null: false
    t.integer  "old_diamond_id"
    t.integer  "old_gemstone_id"
    t.text     "treatment_notes"
    t.string   "orbital_url"
    t.boolean  "whitelisted_video",                               default: true
    t.string   "gdrive_image_url"
    t.string   "gdrive_video_url"
    t.string   "image_source"
    t.string   "image_source_url"
    t.string   "video_source"
    t.string   "video_source_url"
    t.string   "cert_source"
    t.string   "cert_source_url"
    t.text     "source_errors"
    t.string   "jewelry_style"
    t.string   "metal"
    t.string   "mount"
    t.integer  "total_stones"
    t.string   "center_type"
    t.string   "center_gem_type"
    t.string   "center_shape"
    t.string   "center_color"
    t.string   "center_clarity"
    t.string   "center_fancy_color_dominant_color"
    t.string   "center_fancy_color_intensity"
    t.string   "center_fluor_intensity"
    t.string   "center_lab"
    t.string   "center_cert_num"
    t.string   "center_treatment"
    t.integer  "center_total_stones"
    t.decimal  "center_size"
    t.decimal  "center_meas_depth"
    t.decimal  "center_meas_length"
    t.decimal  "center_meas_width"
    t.decimal  "center_meas_ratio"
    t.string   "center_polish"
    t.string   "center_symmetry"
    t.string   "center_cut"
    t.decimal  "center_depth_percent"
    t.decimal  "center_table_percent"
    t.string   "center_pair"
    t.string   "s3_image"
    t.boolean  "image_bad_http_status",                           default: false
    t.datetime "image_check_ran_at"
    t.string   "s3_video"
    t.string   "s3_cert"
    t.text     "s3_direct_upload_url"
    t.integer  "metal_carat"
    t.boolean  "bad_video_content",                               default: false
    t.boolean  "oscillating_video",                               default: false
    t.boolean  "video_bad_http_status",                           default: false
    t.datetime "video_check_ran_at"
    t.boolean  "is_thumb_resized",                                default: false
    t.decimal  "calculated_disc_perc",                            default: 0.0
    t.string   "side_stone_type"
    t.string   "side_stone_gem_type"
    t.integer  "side_stone_total_stones"
    t.decimal  "side_stone_size"
    t.string   "side_stone_shape"
    t.string   "side_stone_color"
    t.string   "side_stone_clarity"
    t.string   "side_stone_fancy_color_dominant_color"
    t.string   "side_stone_fancy_color_intensity"
    t.boolean  "lab_grown",                                       default: false
    t.text     "jewelry_description"
    t.boolean  "lab_sync_status",                                 default: false
    t.jsonb    "owner_info"
    t.integer  "custom_sort_order"
    t.decimal  "parcel_carat_range_from"
    t.decimal  "parcel_carat_range_to"
    t.integer  "layout"
    t.integer  "diamond_category"
    t.string   "pair_stock_num"
    t.integer  "visibility",                            limit: 2
    t.integer  "is_customizable"
    t.string   "growth_type"
    t.string   "tinge"
    t.string   "luster"
    t.string   "location_of_black"
    t.string   "table_inclusion"
    t.string   "table_open"
    t.string   "crown_open"
    t.string   "girdle_open"
    t.string   "pavallion_open"
    t.string   "ownership"
    t.string   "key_to_symbol"
    t.string   "surface_graining"
    t.string   "internal_graining"
    t.string   "indented_natural"
    t.string   "inclusion_pattern"
    t.string   "dor"
    t.decimal  "rapnet_price"
    t.decimal  "lab_sequence_no"
    t.integer  "fm"
    t.string   "intensity_black_code"
    t.string   "natts_code"
    t.string   "original_stone_no"
    t.string   "stock_status"
    t.string   "carat_group"
    t.decimal  "carat_group_seq_no"
    t.decimal  "live_rapa_rate"
    t.string   "stone_detail_url"
    t.datetime "new_arrival_date"
    t.decimal  "shape_sequence_no"
    t.decimal  "color_sequence_no"
    t.decimal  "clarity_sequence_no"
    t.datetime "certificate_date"
    t.datetime "price_date"
    t.boolean  "color_inclusion"
    t.decimal  "csv_discount"
    t.integer  "max_quantity"
    t.string   "price_variant"
    t.integer  "item_tag"
    t.datetime "data_added_on"
    t.string   "diamond_type"
    t.jsonb    "additional_attributes",                           default: {},    null: false
    t.string   "supported_shapes"
    t.string   "scs_sustainable"
    t.string   "scs_climate_neutral"
    t.string   "certification"
    t.integer  "incremental_bid_amount"
    t.integer  "starting_bid"
    t.string   "jewelry_type"
    t.string   "sub_type"
    t.string   "tags"
    t.boolean  "engravable",                            default: false
    t.integer  "parent_id"
    t.string   "tags"
    t.string   "custom_search_text"
    t.integer  "status",                                          default: 0
    t.datetime "status_updated_at"
  end

end
